import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const migrationsDir = path.join(__dirname, '../migrations');

console.log('🔄 Generating MySQL schema file from migrations...');

// Get all migration files sorted by number
const migrationFiles = readdirSync(migrationsDir)
  .filter(file => file.endsWith('.sql') && !file.includes('down'))
  .map(file => {
    const match = file.match(/^(\d+)\.sql$/);
    if (match) {
      return {
        number: parseInt(match[1], 10),
        file: file,
        path: join(migrationsDir, file),
      };
    }
    return null;
  })
  .filter((m): m is { number: number; file: string; path: string } => m !== null)
  .sort((a, b) => a.number - b.number);

console.log(`📋 Found ${migrationFiles.length} migration files`);

let combinedSQL = `-- FocusFlow MySQL Database Schema
-- Generated from migrations
-- DO NOT EDIT THIS FILE - It is auto-generated
-- Run migrations using: npm run migrate

-- Create migrations tracking table
CREATE TABLE IF NOT EXISTS _migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  migration_number INTEGER UNIQUE NOT NULL,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

`;

// Process each migration file
for (const migration of migrationFiles) {
  console.log(`📄 Processing migration ${migration.number}...`);
  
  let sql = readFileSync(migration.path, 'utf-8');
  
  // Convert SQLite syntax to MySQL
  sql = sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'INT AUTO_INCREMENT PRIMARY KEY');
  sql = sql.replace(/AUTOINCREMENT/g, 'AUTO_INCREMENT');
  sql = sql.replace(/DATETIME/g, 'TIMESTAMP');
  sql = sql.replace(/BOOLEAN DEFAULT 0/g, 'BOOLEAN DEFAULT FALSE');
  sql = sql.replace(/BOOLEAN DEFAULT 1/g, 'BOOLEAN DEFAULT TRUE');
  sql = sql.replace(/INTEGER PRIMARY KEY(?!\s+AUTO_INCREMENT)/g, 'INT PRIMARY KEY');
  
  // Add IF NOT EXISTS to CREATE TABLE statements
  sql = sql.replace(/CREATE TABLE (\w+)/g, 'CREATE TABLE IF NOT EXISTS $1');
  
  // Add IF NOT EXISTS to CREATE INDEX statements
  sql = sql.replace(/CREATE INDEX (\w+)/g, 'CREATE INDEX IF NOT EXISTS $1');
  
  // Add migration comment
  combinedSQL += `\n-- Migration ${migration.number}\n`;
  combinedSQL += sql;
  combinedSQL += '\n';
}

// Write to file
const outputPath = path.join(__dirname, '../schema.mysql.sql');
writeFileSync(outputPath, combinedSQL, 'utf-8');

console.log(`✅ MySQL schema file generated: ${outputPath}`);
console.log(`📦 You can now import this file to your MySQL database:`);
console.log(`   mysql -u frankimsocial_ff -p frankimsocial_ff < schema.mysql.sql`);

